### ISSUE TITLE
adding back styling

### ISSUE THREAD

**Issue by kotamine** [kotamine/dairy_maps#1]
I fixed some bugs and regenerated html file (by "knitting" in R), then the html styling John created some time ago disappeared.  

John, could you add back the styling and also make notes on how to do that (if it's easy), so that I could do it myself next time.

**Comment by Johnathannault** [comment]
Since I added code directly to the index.html file, whenever you run the process to compile the project, it deletes everything I added for styling.

**Comment by Johnathannault** [comment]
You can check the last commit I posted to see what code I added back into the file to get the styling back.

**Comment by Johnathannault** [comment]
Make sure everything is still working before we close this issue.

**Comment by kotamine** [comment]
Ok thanks!   I was wondering if there is an easier way (I didn't realize that I should skip the huge content section of HTML code and get to the styling toward the end of the file).  

Could you narrow the white space between sections and then close this issue?   Thanks.

**Comment by kotamine** [comment]
also, could you change the font (unless that's the preferred choice by UMN )?   I guess it's more about the capitalization of section titles etc that  makes it looks so different than the font itself.

**Comment by Johnathannault** [comment]
Done
